# Generated by Django 4.2.3 on 2023-08-08 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_cnt',
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='post.post'),
        ),
    ]
